name: Docker Image CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - uses: actions/checkout@v2
    #- uses: brpaz/hadolint-action@v1.1.0
    #- uses: eshork/gitleaks-action@v1.0.0
    - run: echo ::set-output name=tag_name::$(head -1 Dockerfile | awk '{print $2}' | tr ':' ' '| awk '{print $2}')
      id: tagName
    - uses: anothrNick/github-tag-action@1.29.0
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        RELEASE_BRANCHES: master
        CUSTOM_TAG: ${{ steps.tagName.outputs.tag_name }}
